### ISSUE TITLE
Dynamic playlist "forgets" the parameters I set for a playlist, although still adding songs

### ISSUE THREAD

**Issue by groentebroer** [AF-1/lms-dynamicplaylists#13] opened 2023-09-22 08:29 UTC
## Checklist

:heavy_check_mark: 
---
## DESCRIBE THE BUG
I mostly use the Dynamic playlist generator to use playlist `songs_081_random_not_in_playlist.sql`.
This make me listen to my favorite music while excluding all songs that are not particually my favorites...

After a small fix which got merged, this Dynamic playlist now works perfectly, although when using this playlist for a longer time (e.g. keep it enabled for some days), it starts adding songs that for 100% are in the Ignored playlist, so these songs do not get ignored anymore. (Verified in the playlist .m3u8 file which is safed to disk, and in the SQL DB.)

I cannot really tell why this is happening, but a wild guess would be that the cache (`PlaylistUseCache: 1`) is for some reason gone over time, which then creates a new cache, but with the cache being gone also `PlaylistParameter1` is gone, causing it to not exclude the songs on the ignore playlist anymore.

The good thing though is that the Dynamic playlist keeps adding new songs to the playlists....

## TO REPRODUCE
1. Play: `songs_081_random_not_in_playlist.sql` with a "large" playlist to ignore. 
2. Keep this playing or "paused" a couple of days.
3. Listen to the playlist again, so it will add new songs
4. At some point new songs will include the songs that are in the playlist to ignore.

NOT CERTAIN: But the issue might also be triggered with an "internal" restart of squezeeboxserver after changing some setting. (It asks you if you want to restart, it does not actually restart the linux service, but restarts within the same process or something.)

If I restart the dynamic playlist again, when the issue occurs, it works perfectly again for some time...

## EXPECTED BEHAVIOR
The playlist should keep excluding songs in the "exclude" playlist over time, as the dynamic playlist functionality is still active.

## LOG EXCERPT
I am not sure if any logs might help here, I have none specifically.

## NAME/CODE OF DYNAMIC PLAYLIST
`songs_081_random_not_in_playlist.sql`

## VERSION INFO
* LMS version:  8.3.1
* OS (version): Linux (CentOS 7)
* Plugin version: 4.2.1
* Web skin/controller:  LMS Default, Material, piCorePlayer, SqueezePlay(Slimdevice3)
* Browser (version): Firefox

The problem does not seem skin/web related, I have it with multiple clients (e.g. desktop player, squeezebox, piCorePlayer)

**Comment by AF-1** [comment] 2023-09-22 12:17
First, have you checked if you have enabled the _Don't Stop the Music_ plugin? This plugin would add songs to your client's queue once all dynamic playlist tracks haven been played. BTW I think the latest bug fix stable release is 8.3.**2**.

When you start a dynamic playlist that can use the cache option, DPL will retrieve **all** eligible tracks from the LMS database and cache them. This cache _only_ contains the tracks, i.e. track and artist ids.
Whenever you restart LMS, this cache is wiped - just like the history table (for dynamic playlists that can't use the cache option).

However, the playlist **parameters** of your active dynamic playlist are not part of this cache and are still available. Easy enough to confirm: play some songs from a dynamic playlist that only plays one genre (e.g. songs_003_random_by_genre). Then restart LMS.  Resume playback and DPL will keep adding songs from that one genre only.

So if you restart LMS, the cache is gone and will be recreated. Therefore, you could end up with songs that have been played before. But _**not**_ those from the excluded playllist because they are excluded in the SQLite statement and should therefore not be part of the result set and cache in the first place.

That being said, I haven't been able to reproduce your issue here (8.4.0).
Well, I don't keep players playing, paused or even switched on over days. And I don't have extremely large playlists (how large are we talking anyway?). Not sure if any of this matters though. Since the tracks from the excluded playlist are excluded in the SQLite statement, it's hard to see how they would end up in your mix.

Here's what you could try regrdless: try to recreate your dynamic playlist with the _Dynamic Playlist Creator_ plugin and see if that works better (it uses slightly different SQLite statements). Or create a virtual library with the songs from your excluded playlist and create a dynamic playlist with DPCL that excludes this virtual library. Or add an option to ignore recently played songs.

**Comment by groentebroer** [comment] 2023-09-22 13:21
Wow, thanks for your swift reply @AF-1 !

I have the "Don't stop the music" plugin enabled, but did not see that as the issue because:
1. The current queue playlist got refreshed at the exact of songs I configured it to refresh new items
2. The "Dynamic Playlists" menu stated "Active Dynamic playlist for ...."

Nevertheless I disabled the Don't  stop the music plugin to test without that enabled.
I tried to reproduce the issue by:
* starting the new Dynamic Playlist
* disable the plugin
* let Squeezeboxserver restart to complete
* Let the play queue refresh a couple of times to load new songs (by playing the latest item), which forces refresh.

But I was unable to reproduce it in this way. So we can indeed confirm that with a internal restart, the filtering of the playlist DPL works indeed still as expected.
That leaves the issue occuring after a longer period of time (at least on my end).

I turn my players off and on in between as well, but this picks up the DPL, at least as stated on top of the "Dynamic Playlist" menu.
My "ignore" playlist is 1008 items, so it is not that large. Reason why I said "large" playlist is that you can easily detect abnomalies in the next items that are placed in the queue.

To verify when the issue might occur again;
Is there a way to show the _playlist parameters_ that are active at that moment? (Like in SQL or in Memory, or something?)

Oke, next steps to see if I can further narrow this down will be:
1. If possible, list the _Playlist Parameters_ when it occurs again
2. Try it now "Don't stop the music" is turned off.
3. Use the Dynamic Playlist Creator to see if this gives different results.

Thanks already for your help and your work!

[EDIT]:
I also enabled debug loggin for the plugin if it might occur again, see if that signals something.
[/EDIT]

P.S. 8.3.**1** seems the latest version according to: https://mysqueezebox.com/download

**Comment by groentebroer** [comment] 2023-09-26 10:13
Hi @AF-1 oke, got the same issue again, with logging enabled.

Bear with me, because I cannot make a lot out of it, other then that the exact same query seems to return a different result.....

So the SQL log and result of the first run:
```
server.log-20230924:[23-09-22 16:19:33.1329] Plugins::DynamicPlaylists4::Plugin::getNextDynamicPlaylistTracks (5437) sqlstatement = select tracks.id, tracks.primary_artist from tracks left join library_track on library_track.track = tracks.id join tracks_persistent on tracks_persistent.urlmd5 = tracks.urlmd5 left join dynamicplaylist_history on dynamicplaylist_history.id = tracks.id and dynamicplaylist_history.client = 'xx:xx:xx:xx:xx:xx' where tracks.audio = 1 and tracks.secs >= 90 and dynamicplaylist_history.id is null and case when ('' != '' and '' is not null) then library_track.library = '' else 1 end and case when 0 = 1 then ifnull(tracks_persistent.playCount, 0) = 0 when 0 = 2 then ifnull(tracks_persistent.playCount, 0) > 0 else 1 end and not exists (select * from tracks t3,playlist_track where t3.url = tracks.url and tracks.url = playlist_track.track and playlist_track.playlist = 34599) and not exists (select * from tracks t2,genre_track,genres where t2.id = tracks.id and tracks.id = genre_track.track and genre_track.genre = genres.id and genres.name in ()) group by tracks.id
server.log-20230924-[23-09-22 16:19:57.4627] Plugins::DynamicPlaylists4::Plugin::getNextDynamicPlaylistTracks (5488) sql statement 1: exec time = 24.3286719322205 secs
server.log-20230924-[23-09-22 16:19:57.4640] Plugins::DynamicPlaylists4::Plugin::getNextDynamicPlaylistTracks (5490) Got 6501 track IDs
server.log-20230924-[23-09-22 16:19:57.4656] Plugins::DynamicPlaylists4::Plugin::getTrackIDsForPlaylist (1349) Found 6501 trackIDs for playlist 'Songs - random - ignore songs in selected playlist'
server.log-20230924-[23-09-22 16:19:57.4674] Plugins::DynamicPlaylists4::Plugin::findAndAdd (579) Iteration 1: returned 6501 tracks in 24.4069991111755 seconds
server.log-20230924-[23-09-22 16:19:57.4712] Plugins::DynamicPlaylists4::Plugin::findAndAdd (608) Adding new tracks to total tracks vars exec time = 0.000277042388916016 secs
```

Then after some time (and after logrotate, SqueezeboxServer restart?, etc.)

```
server.log:[23-09-26 11:10:16.0052] Plugins::DynamicPlaylists4::Plugin::getNextDynamicPlaylistTracks (5437) sqlstatement = select tracks.id, tracks.primary_artist from tracks left join library_track on library_track.track = tracks.id join tracks_persistent on tracks_persistent.urlmd5 = tracks.urlmd5 left join dynamicplaylist_history on dynamicplaylist_history.id = tracks.id and dynamicplaylist_history.client = 'xx:xx:xx:xx:xx:xx' where tracks.audio = 1 and tracks.secs >= 90 and dynamicplaylist_history.id is null and case when ('' != '' and '' is not null) then library_track.library = '' else 1 end and case when 0 = 1 then ifnull(tracks_persistent.playCount, 0) = 0 when 0 = 2 then ifnull(tracks_persistent.playCount, 0) > 0 else 1 end and not exists (select * from tracks t3,playlist_track where t3.url = tracks.url and tracks.url = playlist_track.track and playlist_track.playlist = 34599) and not exists (select * from tracks t2,genre_track,genres where t2.id = tracks.id and tracks.id = genre_track.track and genre_track.genre = genres.id and genres.name in ()) group by tracks.id
server.log-[23-09-26 11:10:16.5568] Plugins::DynamicPlaylists4::Plugin::getNextDynamicPlaylistTracks (5488) sql statement 1: exec time = 0.550050020217896 secs
server.log-[23-09-26 11:10:16.5578] Plugins::DynamicPlaylists4::Plugin::getNextDynamicPlaylistTracks (5490) Got 7502 track IDs
server.log-[23-09-26 11:10:16.5598] Plugins::DynamicPlaylists4::Plugin::getTrackIDsForPlaylist (1349) Found 7502 trackIDs for playlist 'Songs - random - ignore songs in selected playlist'
server.log-[23-09-26 11:10:16.5619] Plugins::DynamicPlaylists4::Plugin::findAndAdd (579) Iteration 1: returned 7502 tracks in 0.612381935119629 seconds
server.log-[23-09-26 11:10:16.5641] Plugins::DynamicPlaylists4::Plugin::findAndAdd (608) Adding new tracks to total tracks vars exec time = 0.000284910202026367 secs
```

One of the big differences I noticed at least in the result is the query time. Where it seemed to take **24.x** seconds on the first run, it takes not even **1 second** in the later run.

Could this be actually a bug on the SqueezeboxServer side? That the playlists are not in the (memory?) DB anymore? But only on disk?

Please let me know if we can troubleshoot this any further or that you need a more complete log in a PM. I can offer you the complete logs as well...

**Comment by AF-1** [comment] 2023-09-26 13:09
Hard to tell what's going on without the complete log.
Send me the complete _server.log_ file(s), your _scanner.log_ and your _library.db_ file.
Skimming through large logs is not really sth I enjoy. But I'll try to take a look when I have the time.

BTW this dynamic playlist uses the playlist **id**, not the playlist _name_ (like DPLC) to identify the static playlist. The playlist **id** _can_ change if you do a rescan of any kind while your dynamic playlist is still active (e.g. scheduled auto-rescan). And if LMS assigned the playlist a new id (after a rescan), then your dynamic playlist wouldn't find the static playlist anymore using the old id.

**Comment by groentebroer** [comment] 2023-09-27 07:47
Hi @AF-1, thanks again for you reply.
I think you hit the nail on the head. I have enabled an "automatic" rescan every night, so that causes the issue. So the plugin is working perfectly!

I looked shortly in several tables to see if I could find a way to create my own DPL, based on the playlist name instead of **ID**.
How does DPLC do that? (Sorry to bother you once more.)

**Comment by AF-1** [comment] 2023-09-27 10:27
I only do a manual rescan (wipe/delete) after I've added new tracks to my library or changed the **_file_** tags of tracks already in my LMS library. I never use the auto-rescan option. That's why it didn't come to mind right away.

I suggest you give the DPLC plugin a try. It's very lightweight. The templates let you create custom dynamic playlists with minimal effort and DPLC makes them available to DPL. You don't ever have to deal with SQLite statements. In your case you'd probably use the _Random Tracks - Advanced_ template which has an option to exclude tracks from specified static playlists.
If you're still interested in the SQLite statement of dynamic playlists you've created with DPLC, you'll find them in the DPLC folder (see DPLC FAQ). Since everything seems to be working ok ⭐︎ now, I'll close this. If you have further questions, you can always post in the plugin support threads on the LMS forum.

**Closed as completed by AF-1** 2023-09-27 10:27 UTC
